package Vacunatorio;

public enum Provincia {
    TIERRA_DEL_FUEGO, SANTA_CRUZ, CHUBUT, RIO_NEGRO, NEUQUEN,
    MENDOZA, SAN_LUIS, LA_PAMPA, BUENOS_AIRES, SANTA_FE, ENTRE_RIOS, CORDOBA,
    SAN_JUAN, LA_RIOJA, CATAMARCA, SALTA, JUJUY, CORRIENTES, CHACO, SANTIAGO_DEL_ESTERO,
    MISIONES, FORMOSA, TUCUMAN;
}

